language: python

python:
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get install -y bats
  - pip install -U pip
  - pip install -U numpy scipy Cython

install:
  - python setup.py install

script:
  - bats bats_tests/*.bats
