language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-matplotlib python-numpy python-scipy python-sklearn
  - sudo apt-get install -y bats
script: yes
